### ISSUE TITLE
Download all attachments of all cards

### ISSUE THREAD

**Issue by CodeBrauer** [mattab/trello-backup#16]
Hey there, great script! I've one more idea:

All uploaded attachments are also in the json API.

Example: https://trello.com/b/83y8zuVk.json

```json
/* $json->cards[0]->attachments[0] */
"attachment": {
"url": "https://trello-attachments.s3.amazonaws.com/54f4242c1debe4c0bb3cde00/54f4243fb66cce518998e054/1c0ef63771af72490c29ff8bee46615e/lorem.txt",
"name": "lorem.txt",
"id": "54f424db5d946f84dfd8ce92"
}
```

So this feature would be awesome!

E.g. download all attachments to a folder named by the board an the file has the name of the card. Also check on backup the files already downloaded to not download them again and again.

---

Made an example script here: https://gist.github.com/CodeBrauer/84bce1fdf0ee27e93571

**Comment by CodeBrauer** [comment]
maybe - if there is some time - i will create a pull request.

**Comment by mattab** [comment]
Hi @CodeBrauer 

Sure that's a good idea. Would be great if you can create a Pull request for this :+1:

**Comment by EHJ-52n** [comment]
:+1: 

Are there any updates on this?

**Comment by jtpio** [comment]
I had the same need a while ago.
So if it's urgent you can have a look at this Python script which downloads the attachments: https://github.com/jtpio/trello-full-backup

**Comment by lazartravica** [comment]
I've created the pull request:
https://github.com/mattab/trello-backup/pull/21

Until it is merged you can clone my forked repo:
https://github.com/lazartravica/trello-backup

**Comment by mattab** [comment]
Done in #21 and #24 :+1:
