### ISSUE TITLE
attachments get stored under original Trello board

### ISSUE THREAD

**Issue by spi43984** [mattab/trello-backup#26]
I have many Trello boards and sometimes I copy cards with attachments from one board to another.

If I backup Trello boards the attachments get stored under the original board they originally got attached to and not the board they got copied to.

Not sure yet if this is a script issue or Trello just storing the attachments once under the original board and just linking to the new one.

**Comment by mattab** [comment]
Thank you, fixed in https://github.com/mattab/trello-backup/commit/d2bb5b937ef7190d9cc045f9594e2955b6ad2f4c

**Comment by spi43984** [comment]
Nope, that doesn't fix the issue.

This issue has nothing to do with the wrong path used to store attachments. That's something different. But as said I am not sure if this issue is caused by how the script deals with attachments or how the Trello API works.

If you have two different Trello boards, create a card with attachment in the first board. Then copy this card to the second board.

One would expect to have the same attachments saved loacally for both boards. But that's not what happens. The attachments only get stored for the first board (that one where they originally got attached to).

**Comment by CodeBrauer** [comment]
Seems that this is actually default behaviour of Trello.

trello-backpup searches for attachments in the Activity Feed of each board. However if the board is copied from another this feed is does not contain data from its origin board.

The only way to fix this would be to make an API call for each card of each board.
This would have some small challenges:
- If a board contains 100+ cards with attachments & you have many boards to backup you have to make an [API Rate Limit](https://help.trello.com/article/838-api-rate-limits) check (so each request will be processed)
- To not exceed the rate limit too fast, this could be done using the `/batch` route. So check 10 cards with 1 API call.

**Comment by mattab** [comment]
Thanks @CodeBrauer for your notes and @spi43984 for creating the issue. Considering the complexity, I reckon this won't be implemented or really needed, so will close this. Appreciate your comments!
