### ISSUE TITLE
Attachment's with the same name

### ISSUE THREAD

**Issue by nilsree** [mattab/trello-backup#33]
My organization have multiple board's where multiple screenshot's is pasted into card's.
When doing so the image-attachement will be named _"image.png"_.

The attachment backup will save files with it's original file name, and will therefore overwrite _"image.png"_ multiple times.

I would suggest to create a filename prefix based on the card's name or id, or create a sub folder based on the card's name or id.

**Comment by mattab** [comment]
Good idea, pull request welcome :+1:
