### ISSUE TITLE
application token not resettable by Trello

### ISSUE THREAD

**Issue by ccloquet** [mattab/trello-backup#36]
Hi ! 

Thank you for this great script !

I am just sharing my practise. As Trello does not currently provides a mechanism to reset the application token, I store it in a password manager, and made the following modification to the config.php :

`$application_token = readline ('Application token');`

Is it a good practise ? Would you have a better idea ?

**Comment by CodeBrauer** [comment]
What do you mean by "reset the application token"?
You can revoke you tokens here: https://trello.com/me/account

Also they can be edited/deleted with the Trello API:
https://developers.trello.com/v1.0/reference#tokens
