### ISSUE TITLE
Doesn't backup comments

### ISSUE THREAD

**Issue by directionforward** [mattab/trello-backup#51]
Is this intentional or an issue?

**Comment by mattab** [comment]
it's not intentional, i thought comments would be backed up as well :+1:

**Comment by directionforward** [comment]
Ok thanks for clarifying. Any pointers you can give on getting it to include comments? Thanks.

**Comment by mareklexuan** [comment]
I just checked my export from yesterday and comments are there.

But when I looked for a comment to test it I could not find it as well, but then I realized I forgot about markdowns and line breaks. Maybe that's the issue?

**Comment by directionforward** [comment]
Thanks for the reply @mareklexuan, very helpful.

Had a further search and comments for active cards are in fact being stored. Found them by looking further beyond the markdown.

Somehow the process seems to have skipped some but not all comments for archive cards. Very strange. Closing this.
