### ISSUE TITLE
HTTP/1.1 426 Upgrade Required

### ISSUE THREAD

**Issue by jdownie** [mattab/trello-backup#54]
Your first call to the API (by calling `file_get_contents` against `$url_boards` is failing for me with HTTP 426. I found this by adding `error_reporting(E_ALL)` before that call. Is this something that can be fixed on the client side or something that needs to fixed on their servers?

**Comment by martijnengler** [comment]
Are you running an older version of the code? This was fixed in a6a65a11d960c295a712bbc8449ab23557ee0b71 (see #52 )

**Comment by jdownie** [comment]
Oh, d'oh. I was too. Thanks so much for replying to me so promptly.
