### ISSUE TITLE
PHP Warning:  file_get_contents(...): failed to open stream: HTTP request failed! HTTP/1.1 426 Upgrade Required

### ISSUE THREAD

**Issue by AndreC10002** [mattab/trello-backup#57]
When executing trello-backup I started repeatedly getting the following error message:

PHP Warning:  file_get_contents(...): failed to open stream: HTTP request failed! HTTP/1.1 426 Upgrade Required

I'm running:

PHP 5.6.40-0+deb8u12 (cli) (built: Jun 28 2020 09:37:30)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Any idea what is the reason for that?

Thanks.

**Comment by martijnengler** [comment]
You are probably using an older version of the script. This was fixed in a6a65a1 (see #52 )

**Comment by DanielBloemer** [comment]
I see the same error. I checked the comment from @martijnengler. I use the latest version of the script with that fix. Is there another idea?

Thanks

**Comment by martijnengler** [comment]
You can always check #53, but that does mean switching to `curl`.

**Comment by popod** [comment]
I've the same error only when attachements are downloaded. With `$backup_attachments=true;`. Settings it to `false` does not show any warnings..

**Comment by AndreC10002** [comment]
> 
> 
> I've the same error only when attachements are downloaded. With `$backup_attachments=true;`. Settings it to `false` does not show any warnings..

If you are not downloading attachments, trello-backup won't request anything from AWS, which is the one requiring a newer HTTP version.  But notice, you won't backup your images, spreadsheets, etc, only the boards and cards.

**Comment by AndreC10002** [comment]
Strangely a6a65a1 doesn't work for me.  I need to upgrade my Debian to install a newer version of PHP.

**Comment by DanielBloemer** [comment]
I did a bit of research into this one.
I use the latest version and see, that @popod sees: $backup_attachments=true; leads to the error. I tracked this to line 157:                 file_put_contents($pathForAttachment, file_get_contents($url));
As far as I see this, in this request file_get_contents misses the context, which upgrades this to http 1.1. changing this to
file_get_contents($url, false, $ctx) sets the correct http version but results in a 401. This I wasn't able to fix until now.

**Comment by DanielBloemer** [comment]
The 401 can be fixed by creating a new context for attachments, and add the oauth Header, like in this example:
        $attachmentsContext['http'] = array(
            'protocol_version' => '1.1',
            'header'           => "Authorization: OAuth oauth_consumer_key=\"".$key."\", oauth_token=\"".$application_token."\"\r\n",
        );
        $attachmentsCtx = stream_context_create($attachmentsContext);

**Comment by popod** [comment]
Thanks to @DanielBloemer I've find how to fix the attachments download bug !

I've open PR #61 with the fix.

**Comment by AndreC10002** [comment]
Thank you for working on this much needed fix.  I'll test it right away!

**Comment by AndreC10002** [comment]
Works for me!
